[workspace]
authors = ["ikram98ai <ikram98ai@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo-ml"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
lifev1 = "mojo run life_game/lifev1.mojo"
unilin = "mojo run linear_regression/univariate_regression.mojo"
multilin = "mojo run lifev1.mojo"


[dependencies]
mojo = "<1.0.0"
pygame = ">=2.6.1,<3"
python = ">=3.13.7,<3.14"
polars = ">=1.33.1,<2"
