[workspace]
authors = ["ikram98ai <ikram98ai@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo-ml"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
lifev1 = "mojo run src/life_game/lifev1.mojo"
unilin = "mojo run src/linear_regression/univariate_regression.mojo"
linear = "mojo run src/linear_regression/main.mojo"
logistic = "mojo run src/logistic_regression/main.mojo"


[dependencies]
mojo = "<1.0.0"
pygame = ">=2.6.1,<3"
python = ">=3.13.7,<3.14"
polars = ">=1.33.1,<2"
max = ">=25.7.0.dev2025092705,<26"
